/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CredentialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addIssuer"
      | "anchorCredential"
      | "authorizedIssuers"
      | "credentials"
      | "owner"
      | "removeIssuer"
      | "revokeCredential"
      | "transferOwnership"
      | "verifyCredential"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialAnchored"
      | "CredentialRevoked"
      | "IssuerAdded"
      | "IssuerRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedIssuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "credentials",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCredential",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "addIssuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "anchorCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCredential",
    data: BytesLike
  ): Result;
}

export namespace CredentialAnchoredEvent {
  export type InputTuple = [
    hash: BytesLike,
    issuer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [hash: string, issuer: string, timestamp: bigint];
  export interface OutputObject {
    hash: string;
    issuer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [hash: BytesLike, revoker: AddressLike];
  export type OutputTuple = [hash: string, revoker: string];
  export interface OutputObject {
    hash: string;
    revoker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerAddedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRemovedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialRegistry;
  waitForDeployment(): Promise<this>;

  interface: CredentialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addIssuer: TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;

  anchorCredential: TypedContractMethod<
    [hash: BytesLike],
    [void],
    "nonpayable"
  >;

  authorizedIssuers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  credentials: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        hash: string;
        issuer: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeCredential: TypedContractMethod<
    [hash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyCredential: TypedContractMethod<
    [hash: BytesLike],
    [
      [boolean, string, bigint, boolean] & {
        exists: boolean;
        issuer: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "anchorCredential"
  ): TypedContractMethod<[hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedIssuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        hash: string;
        issuer: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<[hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyCredential"
  ): TypedContractMethod<
    [hash: BytesLike],
    [
      [boolean, string, bigint, boolean] & {
        exists: boolean;
        issuer: string;
        issuedAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CredentialAnchored"
  ): TypedContractEvent<
    CredentialAnchoredEvent.InputTuple,
    CredentialAnchoredEvent.OutputTuple,
    CredentialAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerAdded"
  ): TypedContractEvent<
    IssuerAddedEvent.InputTuple,
    IssuerAddedEvent.OutputTuple,
    IssuerAddedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRemoved"
  ): TypedContractEvent<
    IssuerRemovedEvent.InputTuple,
    IssuerRemovedEvent.OutputTuple,
    IssuerRemovedEvent.OutputObject
  >;

  filters: {
    "CredentialAnchored(bytes32,address,uint256)": TypedContractEvent<
      CredentialAnchoredEvent.InputTuple,
      CredentialAnchoredEvent.OutputTuple,
      CredentialAnchoredEvent.OutputObject
    >;
    CredentialAnchored: TypedContractEvent<
      CredentialAnchoredEvent.InputTuple,
      CredentialAnchoredEvent.OutputTuple,
      CredentialAnchoredEvent.OutputObject
    >;

    "CredentialRevoked(bytes32,address)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "IssuerAdded(address)": TypedContractEvent<
      IssuerAddedEvent.InputTuple,
      IssuerAddedEvent.OutputTuple,
      IssuerAddedEvent.OutputObject
    >;
    IssuerAdded: TypedContractEvent<
      IssuerAddedEvent.InputTuple,
      IssuerAddedEvent.OutputTuple,
      IssuerAddedEvent.OutputObject
    >;

    "IssuerRemoved(address)": TypedContractEvent<
      IssuerRemovedEvent.InputTuple,
      IssuerRemovedEvent.OutputTuple,
      IssuerRemovedEvent.OutputObject
    >;
    IssuerRemoved: TypedContractEvent<
      IssuerRemovedEvent.InputTuple,
      IssuerRemovedEvent.OutputTuple,
      IssuerRemovedEvent.OutputObject
    >;
  };
}
